version: "3.8"
   
services:
    django:
        build: .
        container_name: django
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/usr/src/app/
        ports:
            - "80:80"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 134.122.95.250 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - pgdb
            - redis
    celery:
        build: .
        command: celery -A innovation worker -l INFO
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 134.122.95.250 [::1]
            - CELERY_BROKER=redis://redis:6379/0
            - CELERY_BACKEND=redis://redis:6379/0
        depends_on:
            - django
            - redis
    pgdb:
        image: postgres:9.6
        container_name: pgdb
        environment:
           - 5432:5432
        volumes:
            - pgdata:/var/lib/postgresql/data/
        env_file: ./.env
    redis:
        image: "redis:alpine"
        
volumes:
    pgdata:
